### ISSUE TITLE
Não é possível instalar a gem (Gem não existe no RubyGems ⁉️)

### ISSUE THREAD

**Issue by Victorcorcos** [pirelenito/bovespa_historical#1]
# Passos para reprodução do problema 🦮

1. Add `gem 'bovespa_historical'` to Gemfile
2. `bundle install`

### Resultado 🪲

```rb
Could not find gem 'bovespa_historical' in any of the gem sources listed in your Gemfile.
```

* Essa `gem` não existe mais?

**Comment by pirelenito** [comment]
Olá @Victorcorcos ,

Não atualizo essa gem a mais de 10 anos, e é bem provável que talvez tenha sido removida do RubyGems. Recomendo procurar alternativas ou fazer um fork.

Aproveitei pra arquivar esse repositorio.

Abraço,
